language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install coveralls
  - pip install vcrpy
  - pip install -r requirements.txt
  - python setup.py install
script:
  - coverage run --source poetpy -m py.test
  - coverage report
after_success:
  coveralls