build: false
environment:
  matrix:
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"
install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pip install pytest
  - pip install pyyaml
  - pip install vcrpy
  - pip install pbr
  - pip install -r requirements.txt
  - python setup.py install
test_script:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pytest